export default {
    createNew() {
      var model = {
        khaibaoyteid:0,
        hoten:"",
        cmnd:"",
        gioitinhcode:"",
        dob:"",
        dob_year:"",
        phone:"",
        bhytcode:"",
        email:"",
        quocgia:"",
        diachi_tinh:"",
        diachi_huyen:"",
        diachi_xa:"",
        diachi_chitiet:"",
        loaiphuongtienid:1,
        loaiphuongtien_sohieu:"",
        ngaykhoihanh:"",
        noidi_tinh:"",
        noidi_huyen:"",
        noidi_xa:"",
        noidi_chitiet:"",
        noiden_tinh:"",
        noiden_huyen:"",
        noiden_xa:"",
        noiden_chitiet:"",
        muoibon_ngaydichuyen_id:0,
        muoibon_ngaytiepxuc_id:0,
        thoigiankhaibao:"",
        muoibon_ngaydauhieu:"",
        muoibon_ngaynghingomac:0,
        muoibon_ngaytunuoccobenh:0,
        muoibon_ngaycobieuhien:0,
        tinhtrang_vacxin:0,
        loai_vacxin:"",
        //Chi tiet y te
        khaibaoytechitietid:0,
        ngaydi:"",
        noidi_hc_tinh:"",
        noidi_hc_huyen:"",
        noidi_hc_xa:"",
        noidi_hc_diachichitiet:"",
        ngayden:"",
        noiden_hc_tinh:"",
        noiden_hc_huyen:"",
        noiden_hc_xa:"",
        noiden_hc_diachichitiet:"",
      };
      return model;
    },
  };
  